name: SVK
version: 1.00
abstract: A decentralized version control system
author: Chia-liang Kao <clkao@clkao.org>
license: perl
distribution_type: module
requires:
  Algorithm::Annotate: 0
  Algorithm::Diff: 0
  YAML: 0.38
  Regexp::Shellish: 0
  Data::Hierarchy: 0.21
  File::Temp: 0.14
  Clone: 0
  Pod::Escapes: 0
  Pod::Simple: 0
  PerlIO::via::dynamic: 0.11
  PerlIO::via::symlink: 0.02
  IO::Digest: 0
  SVN::Simple::Edit: 0.27
  Date::Parse: 0
  File::Type: 0
  URI: 0
  PerlIO::eol: 0.13
  Class::Autouse: 1.15
  Getopt::Long: 2.34
  SVN::Mirror: 0.61
no_index:
  directory:
    - inc
provides:
  SVK:
    file: lib/SVK.pm
    version: 1.00
  SVK::Command:
    file: lib/SVK/Command.pm
    version: 1.00
  SVK::Command::Add:
    file: lib/SVK/Command/Add.pm
    version: 1.00
  SVK::Command::Admin:
    file: lib/SVK/Command/Admin.pm
    version: 1.00
  SVK::Command::Annotate:
    file: lib/SVK/Command/Annotate.pm
    version: 1.00
  SVK::Command::Cat:
    file: lib/SVK/Command/Cat.pm
    version: 1.00
  SVK::Command::Checkout:
    file: lib/SVK/Command/Checkout.pm
    version: 1.00
  SVK::Command::Checkout::detach:
    file: lib/SVK/Command/Checkout.pm
    version: 1.00
  SVK::Command::Checkout::list:
    file: lib/SVK/Command/Checkout.pm
    version: 1.00
  SVK::Command::Checkout::relocate:
    file: lib/SVK/Command/Checkout.pm
    version: 1.00
  SVK::Command::Cleanup:
    file: lib/SVK/Command/Cleanup.pm
    version: 1.00
  SVK::Command::Cmerge:
    file: lib/SVK/Command/Cmerge.pm
    version: 1.00
  SVK::Command::Commit:
    file: lib/SVK/Command/Commit.pm
    version: 1.00
  SVK::Command::Copy:
    file: lib/SVK/Command/Copy.pm
    version: 1.00
  SVK::Command::Delete:
    file: lib/SVK/Command/Delete.pm
    version: 1.00
  SVK::Command::Depotmap:
    file: lib/SVK/Command/Depotmap.pm
    version: 1.00
  SVK::Command::Depotmap::add:
    file: lib/SVK/Command/Depotmap.pm
    version: 1.00
  SVK::Command::Depotmap::detach:
    file: lib/SVK/Command/Depotmap.pm
    version: 1.00
  SVK::Command::Depotmap::list:
    file: lib/SVK/Command/Depotmap.pm
    version: 1.00
  SVK::Command::Depotmap::relocate:
    file: lib/SVK/Command/Depotmap.pm
    version: 1.00
  SVK::Command::Describe:
    file: lib/SVK/Command/Describe.pm
    version: 1.00
  SVK::Command::Diff:
    file: lib/SVK/Command/Diff.pm
    version: 1.00
  SVK::Command::Help:
    file: lib/SVK/Command/Help.pm
    version: 1.00
  SVK::Command::Import:
    file: lib/SVK/Command/Import.pm
    version: 1.00
  SVK::Command::Info:
    file: lib/SVK/Command/Info.pm
    version: 1.00
  SVK::Command::List:
    file: lib/SVK/Command/List.pm
    version: 1.00
  SVK::Command::Log:
    file: lib/SVK/Command/Log.pm
    version: 1.00
  SVK::Command::Merge:
    file: lib/SVK/Command/Merge.pm
    version: 1.00
  SVK::Command::Mirror:
    file: lib/SVK/Command/Mirror.pm
    version: 1.00
  SVK::Command::Mirror::detach:
    file: lib/SVK/Command/Mirror.pm
    version: 1.00
  SVK::Command::Mirror::list:
    file: lib/SVK/Command/Mirror.pm
    version: 1.00
  SVK::Command::Mirror::recover:
    file: lib/SVK/Command/Mirror.pm
    version: 1.00
  SVK::Command::Mirror::relocate:
    file: lib/SVK/Command/Mirror.pm
    version: 1.00
  SVK::Command::Mirror::unlock:
    file: lib/SVK/Command/Mirror.pm
    version: 1.00
  SVK::Command::Mirror::upgrade:
    file: lib/SVK/Command/Mirror.pm
    version: 1.00
  SVK::Command::Mkdir:
    file: lib/SVK/Command/Mkdir.pm
    version: 1.00
  SVK::Command::Move:
    file: lib/SVK/Command/Move.pm
    version: 1.00
  SVK::Command::Patch:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::FileRequired:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::apply:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::delete:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::dump:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::list:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::regen:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::test:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::update:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Patch::view:
    file: lib/SVK/Command/Patch.pm
    version: 1.00
  SVK::Command::Propdel:
    file: lib/SVK/Command/Propdel.pm
    version: 1.00
  SVK::Command::Propedit:
    file: lib/SVK/Command/Propedit.pm
    version: 1.00
  SVK::Command::Propget:
    file: lib/SVK/Command/Propget.pm
    version: 1.00
  SVK::Command::Proplist:
    file: lib/SVK/Command/Proplist.pm
    version: 1.00
  SVK::Command::Propset:
    file: lib/SVK/Command/Propset.pm
    version: 1.00
  SVK::Command::Pull:
    file: lib/SVK/Command/Pull.pm
    version: 1.00
  SVK::Command::Push:
    file: lib/SVK/Command/Push.pm
    version: 1.00
  SVK::Command::Resolved:
    file: lib/SVK/Command/Resolved.pm
    version: 1.00
  SVK::Command::Revert:
    file: lib/SVK/Command/Revert.pm
    version: 1.00
  SVK::Command::Smerge:
    file: lib/SVK/Command/Smerge.pm
    version: 1.00
  SVK::Command::Status:
    file: lib/SVK/Command/Status.pm
    version: 1.00
  SVK::Command::Switch:
    file: lib/SVK/Command/Switch.pm
    version: 1.00
  SVK::Command::Sync:
    file: lib/SVK/Command/Sync.pm
    version: 1.00
  SVK::Command::Update:
    file: lib/SVK/Command/Update.pm
    version: 1.00
  SVK::Command::Verify:
    file: lib/SVK/Command/Verify.pm
    version: 1.00
  SVK::Editor::Combine:
    file: lib/SVK/Editor/Combine.pm
    version: 1.00
  SVK::Editor::Delay:
    file: lib/SVK/Editor/Delay.pm
    version: 1.00
  SVK::Editor::Diff:
    file: lib/SVK/Editor/Diff.pm
    version: 1.00
  SVK::Editor::Merge:
    file: lib/SVK/Editor/Merge.pm
    version: 1.00
  SVK::Editor::Patch:
    file: lib/SVK/Editor/Patch.pm
    version: 1.00
  SVK::Editor::Rename:
    file: lib/SVK/Editor/Rename.pm
    version: 1.00
  SVK::Editor::Sign:
    file: lib/SVK/Editor/Sign.pm
  SVK::Editor::Status:
    file: lib/SVK/Editor/Status.pm
    version: 1.00
  SVK::Editor::Translate:
    file: lib/SVK/Editor/Translate.pm
    version: 1.00
  SVK::Editor::XD:
    file: lib/SVK/Editor/XD.pm
    version: 1.00
  SVK::I18N:
    file: lib/SVK/I18N.pm
  SVK::Merge:
    file: lib/SVK/Merge.pm
  SVK::Merge::Info:
    file: lib/SVK/Merge.pm
  SVK::Notify:
    file: lib/SVK/Notify.pm
  SVK::Patch:
    file: lib/SVK/Patch.pm
    version: 1.00
  SVK::Patch::CommitEditor:
    file: lib/SVK/Patch.pm
    version: 1.00
  SVK::Resolve:
    file: lib/SVK/Resolve.pm
  SVK::Resolve::AraxisMerge:
    file: lib/SVK/Resolve/AraxisMerge.pm
  SVK::Resolve::Emacs:
    file: lib/SVK/Resolve/Emacs.pm
  SVK::Resolve::FileMerge:
    file: lib/SVK/Resolve/FileMerge.pm
  SVK::Resolve::GtkDiff:
    file: lib/SVK/Resolve/GtkDiff.pm
  SVK::Resolve::Guiffy:
    file: lib/SVK/Resolve/Guiffy.pm
  SVK::Resolve::KDiff3:
    file: lib/SVK/Resolve/KDiff3.pm
  SVK::Resolve::Meld:
    file: lib/SVK/Resolve/Meld.pm
  SVK::Resolve::P4WinMerge:
    file: lib/SVK/Resolve/P4WinMerge.pm
  SVK::Resolve::TkDiff:
    file: lib/SVK/Resolve/TkDiff.pm
  SVK::Resolve::TortoiseMerge:
    file: lib/SVK/Resolve/TortoiseMerge.pm
  SVK::Resolve::XXDiff:
    file: lib/SVK/Resolve/XXDiff.pm
  SVK::Target:
    file: lib/SVK/Target.pm
    version: 1.00
  SVK::Target::Universal:
    file: lib/SVK/Target/Universal.pm
    version: 1.00
  SVK::Util:
    file: lib/SVK/Util.pm
    version: 1.00
  SVK::VerifyEditor:
    file: lib/SVK/Command/Verify.pm
    version: 1.00
  SVK::XD:
    file: lib/SVK/XD.pm
    version: 1.00
  SVK::XD::Root:
    file: lib/SVK/XD.pm
    version: 1.00
  SVK::XD::Signature:
    file: lib/SVK/XD.pm
    version: 1.00
generated_by: hate-Module::Install version 0.36
