name: SVK
version: 0.17
abstract: A decentralized version control system
author: Chia-liang Kao <clkao@clkao.org>
license: perl
distribution_type: module
requires:
  SVN::Core: 1.0.4
  Algorithm::Annotate: 0
  Text::Diff: 0
  Algorithm::Diff: 0
  YAML: 0
  Regexp::Shellish: 0
  Data::Hierarchy: 0.18
  File::Temp: 0.14
  Clone: 0
  Pod::Escapes: 0
  Pod::Simple: 0
  PerlIO::via::dynamic: 0.02
  SVN::Simple::Edit: 0.21
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
