name: SVK
version: 0.991
abstract: A decentralized version control system
author: Chia-liang Kao <clkao@clkao.org>
license: perl
distribution_type: module
requires:
  Algorithm::Annotate: 0
  Algorithm::Diff: 0
  YAML: 0.36
  Regexp::Shellish: 0
  Data::Hierarchy: 0.21
  File::Temp: 0.14
  Clone: 0
  Pod::Escapes: 0
  Pod::Simple: 0
  PerlIO::via::dynamic: 0.11
  PerlIO::via::symlink: 0.02
  IO::Digest: 0
  SVN::Simple::Edit: 0.27
  Date::Parse: 0
  File::Type: 0
  URI: 0
  PerlIO::eol: 0.13
  Class::Autouse: 1.15
  SVN::Mirror: 0.57
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
